---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  environment:
    ENVIROMENT: production   
    TYPEORM_CONNECTION: postgres 
    TYPEORM_ENTITIES: /home/ubuntu/app/dist/modules/domain/**/*.entity{.ts,.js}
    TYPEORM_MIGRATIONS_DIR: /home/ubuntu/app/dist/migrations
    TYPEORM_MIGRATIONS: /home/ubuntu/app/dist/migrations/*.js
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT')}}"
    TYPEORM_USERNAME:  "{{ lookup('env', 'TYPEORM_USERNAME')}}"
    TYPEORM_PASSWORD:  "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    TYPEORM_DATABASE:  "{{ lookup('env', 'TYPEORM_DATABASE')}}"
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  roles:
    - deploy
