---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_host_key_checking: false
    ansible_stdout_callback: yaml
  environment:
    ENVIROMENT: production   
    TYPEORM_CONNECTION: postgres 
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_MIGRATIONS_DIR: ./src/migrations
    TYPEORM_MIGRATIONS: ./src/migrations/*.ts
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT')}}"
    TYPEORM_USERNAME:  "{{ lookup('env', 'TYPEORM_USERNAME')}}"
    TYPEORM_PASSWORD:  "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    TYPEORM_DATABASE:  "{{ lookup('env', 'TYPEORM_DATABASE')}}"
  
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 600

    - name: "install python for Ansible."
      becme: true 
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false 
      
  roles:
    - deploy
