---
  - name: Create Backend App directory 
    file:
       path: home/ubuntu/backend-app
       state: directory


  - name: Extract artifact 
    unarchive:
      src: artifact.tar.gz
      dest: /home/ubuntu/backend-app

  - name: "Installing Node Dependencies"
    shell: |
      cd  /home/ubuntu/backend-app


  - name: "print env"
    shell: |
      env

  - name: "Executing Node app with PM2"
    shell: |
      cd  /home/ubuntu/backend-app/dist
      pm2 stop default
      pm2 start main.js
    register: execute_node
  - name: print message
    debug: 
      msg: "{{ execute_node.stdout_lines }}"
  - name: "Configure pm2 to start as service"
    become: true 
    shell: |
      sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
      pm2 save
    